from . import periodic_demo
from . import spectral_demo
from . import signals_demo
from . import wav_demo
from . import spectrum_demo
from . import wave_object_demo
from . import signal_object_demo
from . import noise_demo
from . import integrated_spectrum_demo
from . import brownian_demo
from . import pink_noise_demo
from . import gaussian_noise_demo
from . import correlation_demo
from . import serial_correlation_demo
from . import autocorrelation_demo
from . import dot_product_demo
from . import freq_domain_demo
from . import images_as_signals_demo
from . import sampling_demo
from . import dft_demo
from . import convolution_filtering_demo
from . import smoothing_lpf_demo
from . import sharpening_hpf_demo
from . import fft_mechanics_demo
from . import image_processing_intro_demo
from . import overlapping_fields_demo
from . import image_types_formats_demo
from . import intensity_transform_demo
from . import log_transform_demo
from . import gamma_transform_demo
from . import contrast_stretch_demo
from . import thresholding_demo
from . import histogram_processing_demo
from . import histogram_equalization_demo
from . import smoothing_comparison_demo
from . import sharpening_images_demo
from . import derivatives_gradients_demo
from . import laplacian_demo
from . import noise_gradient_demo
from . import sobel_edge_demo
from . import canny_edge_demo
from . import roberts_edge_demo
from . import log_edge_demo
from . import dog_filter_demo
from . import gaussian_pyramid_demo
from . import laplacian_pyramid_demo
from . import erosion_demo
from . import dilation_demo
from . import opening_closing_demo
from . import hit_or_miss_demo
from . import skeleton_demo
from . import convex_hull_demo
from . import remove_objects_demo
from . import tophat_demo
from . import boundary_extraction_demo
from . import grayscale_morphology_demo
from . import feature_extraction_intro_demo
from . import boundary_feature_demo
from . import pca_demo
from . import harris_corner_demo
from . import blob_detection_demo
from . import hog_demo
from . import sift_demo
from . import haar_features_demo
from . import segmentation_intro_demo
from . import hough_transform_demo
from . import hough_circle_demo
from . import advanced_thresholding_demo
from . import otsu_method_demo
from . import edge_segmentation_demo
from . import region_growing_demo
from . import region_splitting_demo
from . import region_merging_demo
from . import watershed_demo
from . import active_contours_demo
from . import morphological_snakes_demo
from . import grabcut_demo